version: "3"
services:
  hmpps-review-send-recall-prototype-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-review-send-recall-prototype-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - HMPPS_PPUD_USERNAME=${HMPPS_PPUD_USERNAME}
      - HMPPS_PPUD_PASSWORD=${HMPPS_PPUD_PASSWORD}
networks:
  hmpps:
